'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {useRouter} from 'next/navigation'
export default function Home(){const r=useRouter();const [session,setSession]=useState<any>(null);const [name,setName]=useState('');const [family,setFamily]=useState<any>(null);const [families,setFamilies]=useState<any[]>([]);const [posts,setPosts]=useState<any[]>([]);const [content,setContent]=useState('');const [busy,setBusy]=useState(false)
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(!data.session)r.push('/login');else{setSession(data.session);load(data.session.user.id)}})},[])
async function load(uid:string){const {data:pf}=await supabase.from('profiles').select('full_name').eq('id',uid).maybeSingle();setName(pf?.full_name||'');const {data:fm}=await supabase.from('family_members').select('family_id,role,families(id,name,description)').eq('user_id',uid);const fs=(fm||[]).map((x:any)=>x.families).filter(Boolean);setFamilies(fs);if(fs[0]){setFamily(fs[0]);const {data:p}=await supabase.from('posts').select('id,content,created_at,author_id').eq('family_id',fs[0].id).order('created_at',{ascending:false});setPosts(p||[])}}
async function createFamily(){if(!name.trim())return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){r.push('/login');return}const {data:f,error}=await supabase.from('families').insert({name:name.trim(),created_by:user.id}).select().single();if(!error&&f){const {error:e}=await supabase.from('family_members').insert({family_id:f.id,user_id:user.id,role:'admin'});if(!e){setFamily(f);setFamilies([f]);}}setBusy(false)}
async function post(){if(!content.trim()||!family||!session)return;const {data:p}=await supabase.from('posts').insert({family_id:family.id,author_id:session.user.id,content}).select().single();if(p){setPosts([p,...posts]);setContent('')}}
if(!session)return null;return <main><header><div><b>العائلة</b><small> al3aela</small></div><nav><button onClick={()=>r.push('/tree')}>🌳 شجرة العائلة</button><button onClick={()=>r.push('/profile')}>👤 ملفي</button><button onClick={async()=>{await supabase.auth.signOut();r.push('/login')}}>خروج</button></nav></header><section className="hero"><h1>أهلاً {name||'بك'} 👋</h1><p>مساحتكم الخاصة للتواصل وحفظ ذكريات العائلة.</p></section>{!family?<section className="card center"><h2>أنشئ عائلتك</h2><p>ابدأ بإنشاء مساحة عائلية ثم أضف أفراد الأسرة.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم العائلة"/><button className="primary" disabled={busy} onClick={createFamily}>إنشاء العائلة</button></section>:<section className="grid"><aside className="card"><h3>عائلتي</h3><div className="family">👨‍👩‍👧‍👦 <span>{family.name}</span></div><button onClick={()=>r.push('/tree')}>فتح شجرة العائلة</button><button onClick={()=>r.push('/profile')}>الملف الشخصي</button></aside><div><section className="card composer"><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="ماذا تريد أن تشارك مع عائلتك؟"/><button className="primary" onClick={post}>نشر</button></section>{posts.map(p=><article className="card post" key={p.id}><div className="avatar">ع</div><div><b>{name||'أحد أفراد العائلة'}</b><small>{new Date(p.created_at).toLocaleString('ar-LY')}</small><p>{p.content}</p></div></article>)}</div></section>}</main>}