'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
import {useRouter} from 'next/navigation'
export default function Profile(){
 const r=useRouter();const [p,setP]=useState<any>({});const [uid,setUid]=useState('');const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState('');
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){r.replace('/login');return}setUid(data.user.id);const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();setP(p||{})})},[])
 async function uploadProfileImage(file:File,type:'avatar'|'cover'){
  if(!file||!uid)return;setUploading(type);try{const ext=file.name.split('.').pop()||'jpg';const path=uid+'/'+type+'-'+Date.now()+'.'+ext;const {error}=await supabase.storage.from('al3aela-media').upload(path,file,{contentType:file.type,upsert:false});if(error){alert(error.message);return}const {data}=supabase.storage.from('al3aela-media').getPublicUrl(path);const field=type==='avatar'?'avatar_url':'cover_url';const {error:dbError}=await supabase.from('profiles').update({[field]:data.publicUrl,updated_at:new Date().toISOString()}).eq('id',uid);if(dbError){alert(dbError.message);return}setP((x:any)=>({...x,[field]:data.publicUrl}))}finally{setUploading('')}
 }
 async function save(){setSaving(true);const {error}=await supabase.from('profiles').update({full_name:p.full_name,bio:p.bio,phone:p.phone,updated_at:new Date().toISOString()}).eq('id',uid);setSaving(false);if(error)alert(error.message);else alert('تم حفظ التغييرات')}
 const initial=(p.full_name||'ع').slice(0,1)
 return <main className="fbapp"><header className="topbar"><button className="brand" onClick={()=>r.push('/')}>العائلة <span>al3aela</span></button><div className="topsearch">🔎 <input placeholder="بحث في العائلة"/></div><nav className="topnav"><button onClick={()=>r.push('/')}>⌂<span>الرئيسية</span></button><button onClick={()=>r.push('/tree')}>🌳<span>الشجرة</span></button><button className="active">👤<span>ملفي</span></button></nav></header>
 <div className="profile-page"><section className="card profile-cover"><div className="cover" style={p.cover_url?{backgroundImage:'url('+p.cover_url+')',backgroundSize:'cover',backgroundPosition:'center'}:undefined}><label className="cover-upload">📷 تغيير الغلاف<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&uploadProfileImage(e.target.files[0],'cover')}/></label></div><div className="profile-hero"><div className="avatar profile-avatar" style={p.avatar_url?{backgroundImage:'url('+p.avatar_url+')',backgroundSize:'cover',backgroundPosition:'center',color:'transparent'}:undefined}>{initial}<label className="avatar-upload">📷<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&uploadProfileImage(e.target.files[0],'avatar')}/></label></div><div><h1>{p.full_name||'ملفي الشخصي'}</h1><p>{p.bio||'عضو في شبكة العائلة'}</p></div></div><div className="profile-tabs"><button className="active">المنشورات</button><button>حول</button><button onClick={()=>r.push('/tree')}>العائلة</button></div></section>
 <section className="profile-grid"><div className="card"><h2>تعديل الملف الشخصي</h2><p>{uploading?'جارٍ رفع الصورة...':'يمكنك إضافة صورة شخصية وصورة غلاف.'}</p><label>الاسم الكامل<input value={p.full_name||''} onChange={e=>setP({...p,full_name:e.target.value})}/></label><label>رقم الهاتف<input value={p.phone||''} onChange={e=>setP({...p,phone:e.target.value})}/></label><label>نبذة عني<textarea value={p.bio||''} onChange={e=>setP({...p,bio:e.target.value})}/></label><button className="primary" onClick={save} disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ التغييرات'}</button></div><div className="card about"><h3>معلومات الحساب</h3><p>👤 عضو في شبكة العائلة</p><p>🆔 معرف المستخدم</p><div className="uid">{uid}</div></div></section></div></main>
}