'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
import {useRouter} from 'next/navigation'
export default function Profile(){
 const r=useRouter();const [p,setP]=useState<any>({});const [uid,setUid]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){r.replace('/login');return}setUid(data.user.id);const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();setP(p||{})})},[])
 async function save(){setSaving(true);const {error}=await supabase.from('profiles').update({full_name:p.full_name,bio:p.bio,phone:p.phone,updated_at:new Date().toISOString()}).eq('id',uid);setSaving(false);if(error)alert(error.message);else alert('تم حفظ التغييرات')}
 const initial=(p.full_name||'ع').slice(0,1)
 return <main className="fbapp"><header className="topbar"><button className="brand" onClick={()=>r.push('/')}>العائلة <span>al3aela</span></button><div className="topsearch">🔎 <input placeholder="بحث في العائلة"/></div><nav className="topnav"><button onClick={()=>r.push('/')}>⌂<span>الرئيسية</span></button><button onClick={()=>r.push('/tree')}>🌳<span>الشجرة</span></button><button className="active">👤<span>ملفي</span></button></nav></header>
 <div className="profile-page"><section className="card profile-cover"><div className="cover"></div><div className="profile-hero"><div className="avatar profile-avatar">{initial}</div><div><h1>{p.full_name||'ملفي الشخصي'}</h1><p>{p.bio||'عضو في شبكة العائلة'}</p></div></div><div className="profile-tabs"><button className="active">المنشورات</button><button>حول</button><button onClick={()=>r.push('/tree')}>العائلة</button></div></section>
 <section className="profile-grid"><div className="card"><h2>تعديل الملف الشخصي</h2><label>الاسم الكامل<input value={p.full_name||''} onChange={e=>setP({...p,full_name:e.target.value})}/></label><label>رقم الهاتف<input value={p.phone||''} onChange={e=>setP({...p,phone:e.target.value})}/></label><label>نبذة عني<textarea value={p.bio||''} onChange={e=>setP({...p,bio:e.target.value})}/></label><button className="primary" onClick={save} disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ التغييرات'}</button></div><div className="card about"><h3>معلومات الحساب</h3><p>👤 عضو في شبكة العائلة</p><p>🆔 معرف المستخدم</p><div className="uid">{uid}</div></div></section></div></main>
}